dateModified: 1656854527
email:
  fromEmail: thomas@passionfruit.be
  fromName: Thomasdelah
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    3f3932bb-cf01-419b-946a-214f142e2ac5: Common # Common
    4d2652b4-24d7-42b1-9b4b-ca9a5719f650: New # New
    235e7c56-172a-4665-beea-9d9569100581: Thomasdelah # Thomasdelah
    344d866f-6a62-4ec2-b3ce-cb4c097f8141: Product # Product
    720be0c2-5111-4530-9f93-29df55dae0c7: Product # Product
    761528e7-9c96-497f-b99d-9bfec8823ccf: Thomasdelah # Thomasdelah
    ab007a35-d6ec-4af0-bff0-1c49d1518171: Dummy # Dummy
    c233a620-07fb-4c92-ad25-061c1c5869db: Description # Description
    ddbdc373-fbfc-4d7b-b163-1afb1189b7a4: Product # Product
plugins:
  commerce:
    edition: pro
    enabled: true
    licenseKey: C3HO806FOM8GUINYORVEOEC6
    schemaVersion: 4.0.1
system:
  edition: pro
  live: true
  name: Thomasdelah
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
